### ISSUE TITLE
ERR_SOCKET_BAD_PORT on new cluster

### ISSUE THREAD

**Issue by zeno-mioso** [soketi/charts#18]
Hello all,

I'm experiencing a strange behavior with this helm chart. For the truth this is the first time that something goes wrong with it, because in the past i've already used it without problems.

`node:internal/validators:217                                                                                                      │
│     throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);                                                                         │
│     ^                                                                                                                             │
│                                                                                                                                   │
│ RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received udp://10.43.244.58:11002.                              │
│     at new NodeError (node:internal/errors:371:5)                                                                                 │
│     at validatePort (node:internal/validators:217:11)                                                                             │
│     at Socket.send (node:dgram:637:12)                                                                                            │
│     at /app/node_modules/node-discover/lib/network.js:188:25                                                                      │
│     at Array.forEach (<anonymous>)                                                                                                │
│     at /app/node_modules/node-discover/lib/network.js:187:26                                                                      │
│     at Network.encode (/app/node_modules/node-discover/lib/network.js:221:12)                                                     │
│     at Network.send (/app/node_modules/node-discover/lib/network.js:180:10)                                                       │
│     at Discover.hello (/app/node_modules/node-discover/lib/discover.js:361:17)                                                    │
│     at /app/node_modules/node-discover/lib/discover.js:286:10 {                                                                   │
│   code: 'ERR_SOCKET_BAD_PORT'`

It seems that even with a values.yaml ( and without ) something  get wrong with PORT. 

Is this a bug? Or am I missing something?

Note : I'm using this in develop env  through a k3d env, traefik based

thanks!

**Comment by zeno-mioso** [comment]
my fault! i just found this: https://github.com/soketi/charts/issues/10

Thanks  anyway!
