### ISSUE TITLE
Unable to deploy Soketi using Helm

### ISSUE THREAD

**Issue by VSuminNeklo** [soketi/charts#32]
EKS Cluster Version: `1.22`
EKS Node Version: `v1.22.17-eks-49d8fe8`
Helm Version: `version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"dirty", GoVersion:"go1.20.2"}`

Steps to reproduce:
1. Deploying application using commands from READ.me
![image](https://user-images.githubusercontent.com/110523019/231786150-456e3a29-3a0e-4c26-accf-805c3cd6b424.png)
2. Getting success message. 
![image](https://user-images.githubusercontent.com/110523019/231786297-8be6f289-1416-47c9-89d0-c22ccab0c14d.png)
3. Expecting working app.

But currently I have broken POD with the message below

```
node:internal/validators:226
    throw new ERR_SOCKET_BAD_PORT(name, port, allowZero);
    ^

RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received udp://172.20.63.90:11002.
    at new NodeError (node:internal/errors:387:5)
    at validatePort (node:internal/validators:226:11)
    at Socket.send (node:dgram:620:12)
    at /app/node_modules/node-discover/lib/network.js:188:25
    at Array.forEach (<anonymous>)
    at /app/node_modules/node-discover/lib/network.js:187:26
    at Network.encode (/app/node_modules/node-discover/lib/network.js:221:12)
    at Network.send (/app/node_modules/node-discover/lib/network.js:180:10)
    at Discover.hello (/app/node_modules/node-discover/lib/discover.js:361:17)
    at /app/node_modules/node-discover/lib/discover.js:286:10 {
  code: 'ERR_SOCKET_BAD_PORT'
}
```

Current POD status is 
`Restarting failing container`

**Comment by madalinignisca** [comment]
Same thing happens to me. Version chart: 1.0.2, app: 1.4.0

**Comment by madalinignisca** [comment]
Found solution suggested in https://github.com/soketi/soketi/discussions/766#discussioncomment-4448878

add in values `nameOverride: "something--u-want"`

**Comment by artem-zherdiev-ingio** [comment]
Ok, but maybe soketi service should have proper name like soketi-service?

**Comment by gamerhashops** [comment]
I can confirm. For some reason overriding nameOverride causes the application to fire.

It would be nice to correct this
